### PR TITLE
Added games

### PR DESCRIPTION
**Pull request by NPCtom**
Images are still required

inFAMOUS Second Son CUSA00223_00
Uncharted: The Nathan Drake Collection CUSA02320_00	
Uncharted 4: A Thief's End CUSA00341_00	
The Order: 1866 CUSA00785_00	
Ratchet & Clank CUSA01047_00

### CODE REVIEW

**Comment by Richm246** [comment]
@NPCtom Would it be possible for you to add Just Cause 3 and Uncharted: The Lost Legacy please?

**Comment by NPCtom** [comment]
@Rich246 Done. Get Tustin to respond to this pull request

**Comment by Alkatarak** [comment]
@NPCtom Hi, can you add Monster Hunter World please ? Thanks for your work

**Comment by Richm246** [comment]
> 
> 
> @Rich246 Done. Get Tustin to respond to this pull request

Thanks

**Comment by Richm246** [comment]
@NPCtom Can you update please? Is it possible you for you add icons or not? It seems @Tustin won't for the requested games.

Can you also add Yakuza 0,  Yakuza Kiwami, Yakuza Kiwami 2 and Judgement please?

**Comment by NPCtom** [comment]
> @NPCtom Can you update please? Is it possible you for you add icons or not? It seems @Tustin won't for the requested games.
> 
> Can you also add Yakuza 0, Yakuza Kiwami, Yakuza Kiwami 2 and Judgement please?

Unfortunately I don't have push rights to the repo so you will have to wait

**Comment by NPCtom** [comment]
@Tustin Were these pushed?

**Comment by Tustin** [comment]
> @Tustin Were these pushed?

Yes sorry. I made some changes to the format for adding custom titles and I added most of the games (not all because I was running low on space).

**Pull request closed without merging**
